In [41]:
from tensorflow.keras.preprocessing.text import one_hot


In [42]:
### sentences 
sent={
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'i am a good boy',
    'i am a good developer',
    'understand the meaning of words',
    'your videos are good',
}

In [43]:
## define the vocabulary size
voc_size=10000

In [44]:
###ONe hot representation

one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[3524, 1009, 2626, 7451],
 [3993, 4955, 7864, 288, 2836],
 [3993, 4955, 7864, 288, 1807],
 [3524, 5227, 2626, 1691],
 [2038, 3524, 668, 2626, 8324],
 [8570, 3570, 2168, 288],
 [3524, 5227, 2626, 7446]]

In [45]:
## word Embedding Representation
from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [46]:
import numpy as np



In [74]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 3524 1009 2626 7451]
 [   0    0    0 3993 4955 7864  288 2836]
 [   0    0    0 3993 4955 7864  288 1807]
 [   0    0    0    0 3524 5227 2626 1691]
 [   0    0    0 2038 3524  668 2626 8324]
 [   0    0    0    0 8570 3570 2168  288]
 [   0    0    0    0 3524 5227 2626 7446]]


In [75]:
## feature representation
dim=10

In [76]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')


c:\Users\Bhavj\Documents\DeepLearningNLP\venv\Lib\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [78]:
model.build(input_shape=(None, sent_length))
model.summary()

Model: "sequential_11"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_11 (Embedding)        │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [51]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 491ms/step


array([[[ 0.01246559,  0.03208907, -0.02433814, -0.01433938,
         -0.01402744,  0.01172196,  0.00225989,  0.00444214,
          0.04524526,  0.01172582],
        [ 0.01246559,  0.03208907, -0.02433814, -0.01433938,
         -0.01402744,  0.01172196,  0.00225989,  0.00444214,
          0.04524526,  0.01172582],
        [ 0.01246559,  0.03208907, -0.02433814, -0.01433938,
         -0.01402744,  0.01172196,  0.00225989,  0.00444214,
          0.04524526,  0.01172582],
        [ 0.01246559,  0.03208907, -0.02433814, -0.01433938,
         -0.01402744,  0.01172196,  0.00225989,  0.00444214,
          0.04524526,  0.01172582],
        [-0.03299682, -0.013142  , -0.01042789,  0.04330769,
         -0.04186082, -0.0494329 ,  0.02177136, -0.04247481,
         -0.0315593 ,  0.04234853],
        [ 0.00429922, -0.00910522,  0.04583127,  0.03995461,
         -0.02872894,  0.04211015,  0.02554662,  0.03779924,
          0.01928652, -0.04974358],
        [-0.04817021,  0.0179078 , -0.00394357,  0.0

In [58]:
embedded_docs[0]

array([   0,    0,    0,    0, 3524, 1009, 2626, 7451])

In [62]:
import numpy as np
model.predict(np.expand_dims(embedded_docs[0], axis=0))


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 89ms/step


array([[[ 0.01246559,  0.03208907, -0.02433814, -0.01433938,
         -0.01402744,  0.01172196,  0.00225989,  0.00444214,
          0.04524526,  0.01172582],
        [ 0.01246559,  0.03208907, -0.02433814, -0.01433938,
         -0.01402744,  0.01172196,  0.00225989,  0.00444214,
          0.04524526,  0.01172582],
        [ 0.01246559,  0.03208907, -0.02433814, -0.01433938,
         -0.01402744,  0.01172196,  0.00225989,  0.00444214,
          0.04524526,  0.01172582],
        [ 0.01246559,  0.03208907, -0.02433814, -0.01433938,
         -0.01402744,  0.01172196,  0.00225989,  0.00444214,
          0.04524526,  0.01172582],
        [-0.03299682, -0.013142  , -0.01042789,  0.04330769,
         -0.04186082, -0.0494329 ,  0.02177136, -0.04247481,
         -0.0315593 ,  0.04234853],
        [ 0.00429922, -0.00910522,  0.04583127,  0.03995461,
         -0.02872894,  0.04211015,  0.02554662,  0.03779924,
          0.01928652, -0.04974358],
        [-0.04817021,  0.0179078 , -0.00394357,  0.0